site_name: C++ Data Structures & Algorithms
site_url: https://idu-international-digital-university.github.io/CPP-Documentation/

nav:
  - Home: index.md
  - Data Structures:
      - Vectors: data_structures/vectors.md
      - Stack: data_structures/stacks.md
      - Queue: data_structures/queues.md
      - Deque: data_structures/deques.md
      - Set: data_structures/sets.md
      - Map: data_structures/maps.md
      - Iterators: data_structures/iterators.md
      - Algorithms: data_structures/algorithms.md

theme:
  name: material
  features:
    # 1.1 Previous / Next tugmalari
    # Material theme avtomatik qoâ€˜llab-quvvatlaydi.
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    # Sticky Sidebar + Scroll highlight
    # Foydalanuvchi qayerda ekanini koâ€˜rib turadi.
    - navigation.sections
    - navigation.expand

  # Light / Dark rejim
  # Materialâ€™da juda chiroyli ishlaydi.
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Light mode

# Sahifa ichida TOC (mundarija)
# Uzun sahifalar uchun ðŸ”¥
markdown_extensions:
  - toc:
      permalink: true
  # Code blockâ€™larni professional qilish
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

# Materialâ€™da instant search bor
plugins:
  - search
